#---------------------------------#
#         version format          #
#---------------------------------#
version: 1.0.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#
os: Windows Server 2012 R2


#---------------------------------#
#            patching             #
#---------------------------------#
assembly_info:
  patch: true
  file: src\Serilog.Sinks.Udp\Properties\AssemblyInfo.cs
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'


#---------------------------------#
#              build              #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

build:
  publish_nuget: true
  verbosity: minimal


#---------------------------------#
#              nuget              #
#---------------------------------#
nuget:
  project_feed: true


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - mattias.kindborg@email.com
    on_build_status_changed: true