#---------------------------------#
#         version format          #
#---------------------------------#
version: 1.0.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#
os: Windows Server 2012 R2


#---------------------------------#
#            patching             #
#---------------------------------#
assembly_info:
  patch: true
  file: src\Serilog.Sinks.Udp\Properties\AssemblyInfo.cs
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'


#---------------------------------#
#              build              #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

skip_tags: true

build:
  publish_nuget: true
  verbosity: minimal


#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - cmd: set SOLUTION=Serilog.Sinks.Udp.sln
  - cmd: set PROJECT=src\Serilog.Sinks.Udp\Serilog.Sinks.Udp.csproj
  - cmd: set LOGGER=C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll

  - cmd: msbuild %SOLUTION% /t:Rebuild /p:Configuration=Release;TargetFrameworkVersion=v4.0 /m /logger:"%LOGGER%"
  - cmd: msbuild %SOLUTION% /t:Rebuild /p:Configuration=Release;TargetFrameworkVersion=v4.5 /m /logger:"%LOGGER%"
  
  - cmd: nuget pack -Prop Configuration=Release %PROJECT%


#---------------------------------#
#              nuget              #
#---------------------------------#
nuget:
  project_feed: true


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  # Email
  - provider: Email
    to:
      - mattias.kindborg@email.com
    on_build_status_changed: true