image: Visual Studio 2019

version: '{build}'

configuration: Release

build_script:
  - ps: ./build/build.ps1

test: off

artifacts:
  - path: artifacts/Serilog.*.*nupkg
    name: NuGet
    type: NuGetPackage

deploy:
  - provider: GitHub
    tag: ${APPVEYOR_REPO_TAG_NAME}
    release: Release ${APPVEYOR_REPO_TAG_NAME}
    description: TODO
    auth_token:
      secure: jFJL5c0XhkqkyH01r1SccqQpVdJGQ8AU0sT7Rg12f/QuO+RNa6870wyMjUWGeJZJ
    artifact: NuGet
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    api_key:
      secure: ISvomClU+lG1ebfbTdJd8zQym+yfZR6CMuEWx5ukBwH+qCdzqmEVg+nCBfd1mLOQ
    symbol_server: https://www.nuget.org
    skip_symbols: false
    on:
      APPVEYOR_REPO_TAG: true
