image: Visual Studio 2022

version: '{build}'

configuration: Release

build_script:
  - ps: ./build/build.ps1

test: off

artifacts:
  - path: artifacts/Serilog.*.*nupkg
    name: NuGet
    type: NuGetPackage

deploy:
  - provider: GitHub
    tag: ${APPVEYOR_REPO_TAG_NAME}
    release: Release ${APPVEYOR_REPO_TAG_NAME}
    description: TODO
    auth_token:
      secure: Silg+YGieKmNn2pyQkiT7nnG4wBbrZM5eWDSCn+c9jdE9licmLnbNz/2CGMr+ywl
    artifact: NuGet
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    api_key:
      secure: gNWP8JjhH3b4424O6aMt2Aamy6KIJI5nmv4UVnVYW3es3OA7DQ3ULml+ChO73Lwa
    symbol_server: https://www.nuget.org
    skip_symbols: false
    on:
      APPVEYOR_REPO_TAG: true
